- name: Remove ula_prefix
  uci:
    command: delete
    key: network.globals.ula_prefix
  ignore_errors: true

- name: Remove wan interface
  uci:
    command: delete
    key: network.wan
  notify:
  - Commit changes
  - Restart network
  ignore_errors: true

- name: Remove wan6 interface
  uci:
    command: delete
    key: network.wan6
  notify:
  - Commit changes
  - Restart network
  ignore_errors: true

- name: Remove lan interface
  uci:
    command: delete
    key: network.lan
  ignore_errors: true

- name: Set IP Address, gateway and dns
  uci:
    command: section
    config: network
    type: interface
    name: lan
    value:
      device: 'br-lan'
      proto: 'static'
      netmask: '255.255.255.0'
      ipaddr: "{{ ansible_host }}"
      gateway: "{{ network.gateway }}"

- name: Set dns to primary
  uci:
    command: add_list
    key: network.lan.dns
    value: "{{ network.gateway }}"
  notify:
    - Commit changes
    - Restart network

- name: Stop and disable firewall
  raw: /etc/init.d/firewall stop && /etc/init.d/firewall disable

- name: Instead of disabling dnsmasq (required by TFTP)
  uci:
    command: set
    key: dhcp.lan
    value:
      ignore: 1
  notify:
    - Commit changes
    - Restart dhcp

- name: Stop and disable odhcpd
  raw: /etc/init.d/odhcpd stop && /etc/init.d/odhcpd disable