---
- name: Set local domain
  uci:
    command: set
    key: "dhcp.@dnsmasq[0]"
    value: 
      domain: "{{ network.local_domain }}"
      local: "/{{ network.local_domain }}/"
  notify:
    - Commit changes
    - Restart service

- name: Delete old static leases
  raw: "while uci -q delete dhcp.host[0]; do :; done"
  notify:
  - Commit changes

- name: Configure static clients
  uci: 
    command: section
    config: dhcp
    type: host
    find_by:
      name: "{{ item.hostname }}"
    value:
      name: "{{ item.hostname }}"
      ip: "{{ item.ip }}"
      mac: "{{ item.mac }}"
      dns: '1'
      duid: "{{ item.duid | default('') }}"
  loop: "{{ network.static_clients }}"
  notify:
  - Commit changes
  - Restart service
...