- name: Remove pre-existing Rule
  uci:
    command: delete
    config: firewall
  notify:
    - Commit firewall
    - Restart firewall
  ignore_errors: true

- name: Add Rule
  uci:
    command: section
    config: firewall
    type: rule
    find_by:
      name: Allow-WireGuard
    value:
      name: Allow-WireGuard
      src: wan
      dest_port: "{{ wireguard.server.port }}"
      proto: udp
      target: ACCEPT
  notify:
    - Commit firewall
    - Restart firewall
